// Tradução das categorias da Pluggy (vêm em inglês) para pt-BR
const MAP: Record<string, string> = {
  Shopping: "Compras",
  "Online shopping": "Compras online",
  Transfers: "Transferências",
  "Same person transfer": "Entre contas próprias (não conta)",
  "Eating out": "Restaurantes",
  Investments: "Investimentos",
  "Digital services": "Serviços digitais",
  Services: "Serviços",
  "Gas stations": "Combustível",
  Groceries: "Mercado",
  "Food delivery": "Delivery",
  "Food and drinks": "Alimentação",
  "Tax on financial operations": "IOF e taxas",
  "Vehicle maintenance": "Manutenção do carro",
  Leisure: "Lazer",
  Travel: "Viagem",
  Health: "Saúde",
  Education: "Educação",
  Telecommunications: "Telefonia e internet",
  Rent: "Aluguel",
  Utilities: "Contas de casa",
  Income: "Renda",
  Salary: "Salário",
  Loans: "Empréstimos",
  "Loans and financing": "Empréstimos",
  Insurance: "Seguros",
  "Credit card payment": "Pagamento de fatura",
  Entertainment: "Entretenimento",
  Taxes: "Impostos",
  "Bank fees": "Tarifas bancárias",
  Pharmacy: "Farmácia",
  Transport: "Transporte",
  "Public transport": "Transporte público",
  "Taxi and ride-hailing": "Táxi e apps",
  Clothing: "Vestuário",
  Pets: "Pets",
  Gym: "Academia",
  "Gyms and fitness centers": "Academia",
  Donations: "Doações",
  "Fixed income investment": "Renda fixa",
  "Variable income investment": "Renda variável",
  Legal: "Jurídico",
  Housing: "Moradia",
  Electronics: "Eletrônicos",
  Automotive: "Automotivo",
  Accomodation: "Hospedagem",
  Gambling: "Apostas",
  Healthcare: "Saúde",
  Wellness: "Bem-estar",
  "Wellness and fitness": "Bem-estar e fitness",
  Electricity: "Energia elétrica",
  Internet: "Internet",
  "Interests charged": "Juros cobrados",
  "Late payment and overdraft costs": "Multas e juros por atraso",
  "Transfer - PIX": "Transferência PIX",
  "Transfer - Foreign Exchange": "Câmbio",
  "Pet supplies and vet": "Pet e veterinário",
  Cashback: "Cashback",
  "Video streaming": "Streaming de vídeo",
  "Mutual funds": "Fundos de investimento",
  Transportation: "Transporte",
  "Cinema, theater and concerts": "Cinema, teatro e shows",
  Bakery: "Padaria",
  "Supplier payments": "Fornecedores e empresas",
  Parking: "Estacionamento",
  "Tolls and in vehicle payment": "Pedágio e pagamentos no veículo",
};

export function translateCategory(cat: string | null | undefined): string {
  if (!cat) return "Sem categoria";
  return MAP[cat] ?? cat;
}
